import type { Business } from '@/types/business'

export const mockBusinesses: Business[] = [
  {
    id: 1,
    name: 'Al Barakah Kerala Restaurant',
    nameMl: 'അൽ ബറക്ക കേരള റസ്റ്റോറന്റ്',
    slug: 'al-barakah-kerala-restaurant',
    category: 'Restaurants & Food',
    categoryMl: 'റസ്റ്റോറന്റ് & ഭക്ഷണം',
    categorySlug: 'restaurants',
    location: 'Deira, Dubai',
    locationMl: 'ദേര, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Al Rigga Road, Deira, Dubai',
    phone: '+971 4 234 5678',
    whatsapp: '+971 50 234 5678',
    website: 'https://albarakah.ae',
    email: 'info@albarakah.ae',
    rating: 4.8,
    reviewCount: 342,
    priceRange: 2,
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=100&q=80',
    photos: [
      'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80&auto=format&fit=crop',
    ],
    description: 'Authentic Kerala cuisine in the heart of Dubai. Famous for Malabar biryani, seafood curry, and Kerala sadya. Family-friendly atmosphere with private dining available.',
    descriptionMl: 'ദുബായ് ഹൃദയത്തിൽ ആധികാരിക കേരള ഭക്ഷണം. മലബാർ ബിരിയാണി, കടൽ ഭക്ഷണ കറി, കേരള സദ്യ എന്നിവയ്ക്ക് പ്രശസ്തം.',
    tags: ['Biryani', 'Seafood', 'Kerala Sadya', 'Halal', 'Delivery'],
    tagsMl: ['ബിരിയാണി', 'കടൽ ഭക്ഷണം', 'കേരള സദ്യ', 'ഹലാൽ', 'ഡെലിവറി'],
    verified: true,
    featured: true,
    premium: true,
    open: true,
    hours: '8:00 AM – 11:30 PM',
    established: 2009,
    employees: '20-50',
    languages: ['Malayalam', 'English', 'Arabic', 'Hindi'],
  },
  {
    id: 2,
    name: 'Kerala Properties Dubai',
    nameMl: 'കേരള പ്രോപ്പർടീസ് ദുബായ്',
    slug: 'kerala-properties-dubai',
    category: 'Real Estate',
    categoryMl: 'റിയൽ എസ്റ്റേറ്റ്',
    categorySlug: 'real-estate',
    location: 'Business Bay, Dubai',
    locationMl: 'ബിസിനസ് ബേ, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Executive Tower, Business Bay, Dubai',
    phone: '+971 4 345 6789',
    whatsapp: '+971 55 345 6789',
    rating: 4.9,
    reviewCount: 186,
    priceRange: 3,
    image: 'https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=800&q=80&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?w=100&q=80',
    photos: [
      'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400&q=80&auto=format&fit=crop',
    ],
    description: 'Trusted real estate consultancy for NRIs investing in Kerala and UAE properties. Specializing in residential and commercial properties with end-to-end legal support.',
    descriptionMl: 'കേരളത്തിലും യുഎഇയിലും നിക്ഷേപം നടത്തുന്ന NRI-കൾക്ക് വിശ്വസ്ത കൺസൽറ്റൻസി.',
    tags: ['NRI Investment', 'Kerala Homes', 'UAE Property', 'Legal Support'],
    tagsMl: ['NRI നിക്ഷേപം', 'കേരള ഭവനം', 'UAE പ്രോപ്പർടി'],
    verified: true,
    featured: true,
    premium: true,
    open: true,
    hours: '9:00 AM – 6:00 PM (Mon–Sat)',
    established: 2012,
    employees: '10-20',
    languages: ['Malayalam', 'English', 'Arabic'],
  },
  {
    id: 3,
    name: 'Malabar Medical Centre',
    nameMl: 'മലബാർ മെഡിക്കൽ സെന്റർ',
    slug: 'malabar-medical-centre',
    category: 'Healthcare',
    categoryMl: 'ആരോഗ്യ സേവനം',
    categorySlug: 'healthcare',
    location: 'Al Nahda, Sharjah',
    locationMl: 'അൽ നഹ്ദ, ഷാർജ',
    emirate: 'Sharjah',
    emirateSlug: 'sharjah',
    address: 'Al Nahda 1, Sharjah',
    phone: '+971 6 533 4455',
    whatsapp: '+971 52 533 4455',
    rating: 4.7,
    reviewCount: 521,
    priceRange: 2,
    image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Comprehensive medical care with Malayalam-speaking doctors available 24/7. Specialties include General Practice, Gynaecology, Paediatrics, and Dentistry.',
    descriptionMl: 'മലയാളം സംസാരിക്കുന്ന ഡോക്ടർമാർ 24/7 ലഭ്യമായ സമഗ്ര വൈദ്യ സേവനം.',
    tags: ['General Practice', 'Gynaecology', 'Paediatrics', 'Dentistry', '24/7'],
    tagsMl: ['ജനറൽ പ്രാക്ടീസ്', 'ഗൈനക്കോളജി', 'ദന്ത ചികിത്സ', '24/7'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: 'Open 24 Hours',
    established: 2005,
    employees: '50-100',
    languages: ['Malayalam', 'English', 'Arabic', 'Hindi', 'Urdu'],
  },
  {
    id: 4,
    name: 'Keraleeyam Sweets & Bakery',
    nameMl: 'കേരളീയം സ്വീറ്റ്സ് & ബേക്കറി',
    slug: 'keraleeyam-sweets-bakery',
    category: 'Restaurants & Food',
    categoryMl: 'റസ്റ്റോറന്റ് & ഭക്ഷണം',
    categorySlug: 'restaurants',
    location: 'Al Qusais, Dubai',
    locationMl: 'അൽ കുസൈസ്, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Al Qusais Industrial Area, Dubai',
    phone: '+971 4 267 8901',
    whatsapp: '+971 56 267 8901',
    rating: 4.6,
    reviewCount: 278,
    priceRange: 1,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Traditional Kerala sweets, halwa, and baked goods. Special bulk orders for weddings and events. Authentic recipes passed down for generations.',
    descriptionMl: 'പരമ്പരാഗത കേരള മധുരങ്ങൾ, ഹൽവ, ബേക്ക്ഡ് ഗുഡ്സ്. ചടങ്ങുകൾക്ക് ബൾക്ക് ഓർഡർ.',
    tags: ['Kerala Sweets', 'Halwa', 'Wedding Orders', 'Delivery'],
    tagsMl: ['കേരള മധുരം', 'ഹൽവ', 'വിവാഹ ഓർഡർ'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: '7:00 AM – 10:00 PM',
    established: 2015,
    employees: '5-10',
    languages: ['Malayalam', 'Hindi', 'English'],
  },
  {
    id: 5,
    name: 'Gulf Malayali Finance',
    nameMl: 'ഗൾഫ് മലയാളി ഫിനാൻസ്',
    slug: 'gulf-malayali-finance',
    category: 'Finance & Banking',
    categoryMl: 'ധനകാര്യം & ബാങ്കിംഗ്',
    categorySlug: 'finance',
    location: 'DIFC, Dubai',
    locationMl: 'DIFC, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Gate Village, DIFC, Dubai',
    phone: '+971 4 456 7890',
    website: 'https://gulfmalayalifinance.ae',
    rating: 4.8,
    reviewCount: 142,
    priceRange: 3,
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'NRI banking, remittance, insurance and investment advisory services. SEBI-registered advisors helping Malayalis build wealth in India and UAE.',
    descriptionMl: 'NRI ബാങ്കിംഗ്, റെമിറ്റൻസ്, ഇൻഷുറൻസ്, നിക്ഷേപ ഉപദേശ സേവനങ്ങൾ.',
    tags: ['NRI Services', 'Remittance', 'Investment', 'Insurance'],
    tagsMl: ['NRI സേവനം', 'റെമിറ്റൻസ്', 'നിക്ഷേപം'],
    verified: true,
    featured: true,
    premium: true,
    open: false,
    hours: '9:00 AM – 5:30 PM (Mon–Fri)',
    established: 2018,
    employees: '10-20',
    languages: ['Malayalam', 'English'],
  },
  {
    id: 6,
    name: 'Trivandrum Tech Solutions',
    nameMl: 'തിരുവനന്തപുരം ടെക് സൊലൂഷൻസ്',
    slug: 'trivandrum-tech-solutions',
    category: 'Technology',
    categoryMl: 'ടെക്നോളജി',
    categorySlug: 'technology',
    location: 'Internet City, Dubai',
    locationMl: 'ഇന്റർനെറ്റ് സിറ്റി, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Building 3, Dubai Internet City',
    phone: '+971 4 567 8901',
    website: 'https://tts.ae',
    rating: 4.7,
    reviewCount: 89,
    priceRange: 3,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Web development, mobile apps, and IT solutions by Malayali engineers. Serving SMEs across UAE with custom software, e-commerce and digital marketing.',
    descriptionMl: 'മലയാളി എഞ്ചിനിയർമാർ ചെയ്യുന്ന വെബ് ഡെവലപ്മെന്റ്, മൊബൈൽ ആപ്പ്, ഐടി സൊലൂഷൻ.',
    tags: ['Web Development', 'Mobile Apps', 'E-commerce', 'IT Support'],
    tagsMl: ['വെബ് ഡെവലപ്മെന്റ്', 'മൊബൈൽ ആപ്പ്'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: '9:00 AM – 6:00 PM (Mon–Sat)',
    established: 2016,
    employees: '10-20',
    languages: ['Malayalam', 'English'],
  },
  {
    id: 7,
    name: 'Kozhikode Legal Consultants',
    nameMl: 'കോഴിക്കോട് ലീഗൽ കൺസൾട്ടന്റ്സ്',
    slug: 'kozhikode-legal-consultants',
    category: 'Legal Services',
    categoryMl: 'നിയമ സേവനങ്ങൾ',
    categorySlug: 'legal',
    location: 'Bur Dubai, Dubai',
    locationMl: 'ബർ ദുബായ്, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Khalid Bin Waleed Rd, Bur Dubai',
    phone: '+971 4 678 9012',
    rating: 4.5,
    reviewCount: 67,
    priceRange: 3,
    image: 'https://images.unsplash.com/photo-1589519160732-576fc045d8e4?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Expert legal services in UAE and Kerala law. Specializing in visa issues, business setup, property disputes, and power of attorney for NRIs.',
    descriptionMl: 'UAE, കേരള നിയമ വിദഗ്ദ്ധ സേവനം. വിസ, ബിസിനസ് സെറ്റ്അപ്പ്, NRI POA.',
    tags: ['Visa', 'Business Setup', 'Property Law', 'NRI Legal', 'POA'],
    tagsMl: ['വിസ', 'ബിസിനസ് സെറ്റ്അപ്പ്', 'NRI'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: '9:00 AM – 7:00 PM (Sun–Thu)',
    established: 2011,
    employees: '5-10',
    languages: ['Malayalam', 'English', 'Arabic'],
  },
  {
    id: 8,
    name: 'Calicut Catering Services',
    nameMl: 'കോഴിക്കോട് കേറ്ററിംഗ് സർവ്വീസസ്',
    slug: 'calicut-catering-services',
    category: 'Restaurants & Food',
    categoryMl: 'റസ്റ്റോറന്റ് & ഭക്ഷണം',
    categorySlug: 'restaurants',
    location: 'Muweilah, Sharjah',
    locationMl: 'മുവൈല, ഷാർജ',
    emirate: 'Sharjah',
    emirateSlug: 'sharjah',
    address: 'Muweilah Commercial, Sharjah',
    phone: '+971 6 544 3322',
    whatsapp: '+971 50 544 3322',
    rating: 4.6,
    reviewCount: 198,
    priceRange: 2,
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Full-service Kerala catering for weddings, corporate events, and social gatherings. Sadya, biryani, and continental menus available for 50–5000 guests.',
    descriptionMl: 'വിവാഹം, ഓഫീസ് പരിപാടി, സദ്യ, ബിരിയാണി 50 മുതൽ 5000 അതിഥികൾ വരെ.',
    tags: ['Wedding Catering', 'Kerala Sadya', 'Corporate Events', 'Biryani'],
    tagsMl: ['വിവാഹ കേറ്ററിംഗ്', 'കേരള സദ്യ'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: 'By Appointment',
    established: 2013,
    employees: '10-20',
    languages: ['Malayalam', 'Hindi', 'English'],
  },
  {
    id: 9,
    name: 'MK Builders UAE',
    nameMl: 'MK ബിൽഡേഴ്സ് UAE',
    slug: 'mk-builders-uae',
    category: 'Construction',
    categoryMl: 'നിർമ്മാണം',
    categorySlug: 'construction',
    location: 'Al Quoz, Dubai',
    locationMl: 'അൽ ഖൊസ്, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Al Quoz Industrial Area 3, Dubai',
    phone: '+971 4 789 0123',
    whatsapp: '+971 54 789 0123',
    rating: 4.4,
    reviewCount: 112,
    priceRange: 3,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Turnkey villa and apartment construction in Kerala and UAE fit-out. Specializing in interior design, renovation, and commercial fit-outs across Dubai.',
    descriptionMl: 'കേരള-UAE ടേൺകി നിർമ്മാണം, ഇന്റീരിയർ ഡിസൈൻ, നവീകരണം.',
    tags: ['Villa Construction', 'Interior Design', 'Renovation', 'Kerala Homes'],
    tagsMl: ['വില്ല നിർമ്മാണം', 'ഇന്റീരിയർ ഡിസൈൻ'],
    verified: false,
    featured: false,
    premium: false,
    open: true,
    hours: '8:00 AM – 6:00 PM (Mon–Sat)',
    established: 2010,
    employees: '50-100',
    languages: ['Malayalam', 'Hindi', 'English'],
  },
  {
    id: 10,
    name: 'Nair Beauty Lounge',
    nameMl: 'നായർ ബ്യൂട്ടി ലൗഞ്ച്',
    slug: 'nair-beauty-lounge',
    category: 'Beauty & Wellness',
    categoryMl: 'സൗന്ദര്യം & ആരോഗ്യം',
    categorySlug: 'beauty',
    location: 'Karama, Dubai',
    locationMl: 'കരാമ, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Al Karama Street, Dubai',
    phone: '+971 4 890 1234',
    whatsapp: '+971 55 890 1234',
    rating: 4.7,
    reviewCount: 304,
    priceRange: 2,
    image: 'https://images.unsplash.com/photo-1607008829749-c0f284a49fc4?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Premium beauty salon offering Kerala Ayurvedic treatments, bridal packages, hair care, and skin treatments by experienced Malayalam-speaking beauticians.',
    descriptionMl: 'കേരള ആയുർവേദ ട്രീറ്റ്‌മെന്റ്, ബ്രൈഡൽ, ഹെയർ കെയർ, സ്കിൻ ട്രീറ്റ്‌മെന്റ്.',
    tags: ['Ayurvedic', 'Bridal', 'Hair Care', 'Skin Treatments', 'Facials'],
    tagsMl: ['ആയുർവേദം', 'ബ്രൈഡൽ', 'ഹെയർ കെയർ'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: '9:00 AM – 9:00 PM',
    established: 2017,
    employees: '5-10',
    languages: ['Malayalam', 'English', 'Hindi'],
  },
  {
    id: 11,
    name: 'Kerala Motor Garage',
    nameMl: 'കേരള മോട്ടോർ ഗരേജ്',
    slug: 'kerala-motor-garage',
    category: 'Automotive',
    categoryMl: 'ഓട്ടോമോട്ടീവ്',
    categorySlug: 'automotive',
    location: 'Ras Al Khor, Dubai',
    locationMl: 'റാസ് അൽ ഖോർ, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Ras Al Khor Industrial Area 2, Dubai',
    phone: '+971 4 901 2345',
    whatsapp: '+971 50 901 2345',
    rating: 4.5,
    reviewCount: 167,
    priceRange: 2,
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Full-service auto repair, maintenance, and detailing. Specialists in Japanese and European vehicles. Free pick-up & drop service within Dubai.',
    descriptionMl: 'ഓട്ടോ റിപ്പെയർ, മെയ്ന്റനൻസ്, ഡീറ്റെയ്‌ലിംഗ്. ദുബായ് മുഴുവൻ സൗജന്യ പിക്ക്-അപ്പ്.',
    tags: ['Car Repair', 'Maintenance', 'Detailing', 'Free Pickup'],
    tagsMl: ['കാർ റിപ്പെയർ', 'ഡീറ്റെയ്‌ലിംഗ്'],
    verified: false,
    featured: false,
    premium: false,
    open: false,
    hours: '7:30 AM – 8:00 PM (Sun–Fri)',
    established: 2008,
    employees: '10-20',
    languages: ['Malayalam', 'Hindi', 'English', 'Arabic'],
  },
  {
    id: 12,
    name: 'Thrissur Travels & Tourism',
    nameMl: 'തൃശ്ശൂർ ട്രാവൽസ് & ടൂറിസം',
    slug: 'thrissur-travels-tourism',
    category: 'Travel & Tourism',
    categoryMl: 'ടൂറിസം & യാത്ര',
    categorySlug: 'travel',
    location: 'Deira, Dubai',
    locationMl: 'ദേര, ദുബായ്',
    emirate: 'Dubai',
    emirateSlug: 'dubai',
    address: 'Al Maktoum Street, Deira, Dubai',
    phone: '+971 4 012 3456',
    whatsapp: '+971 56 012 3456',
    website: 'https://thrissurtravels.ae',
    rating: 4.6,
    reviewCount: 231,
    priceRange: 2,
    image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80&auto=format&fit=crop',
    photos: [],
    description: 'Full-service travel agency specializing in Kerala holiday packages, Hajj & Umrah, visa processing, and corporate travel management for UAE residents.',
    descriptionMl: 'കേരള ഹോളിഡേ പാക്കേജ്, ഹജ്ജ് & ഉംറ, വിസ പ്രോസസ്സിംഗ്, കോർപ്പറേറ്റ് ട്രാവൽ.',
    tags: ['Kerala Packages', 'Hajj & Umrah', 'Visa Services', 'Corporate Travel'],
    tagsMl: ['കേരള പാക്കേജ്', 'ഹജ്ജ് & ഉംറ', 'വിസ'],
    verified: true,
    featured: false,
    premium: false,
    open: true,
    hours: '8:30 AM – 8:30 PM',
    established: 2004,
    employees: '10-20',
    languages: ['Malayalam', 'English', 'Arabic', 'Hindi'],
  },
]

// Slugs match exactly what's in the Supabase categories table
export const categories = [
  { slug: 'restaurants-food',       name: 'Restaurants & Food',       nameMl: 'റസ്റ്റോറന്റ് & ഭക്ഷണം',        count: 0 },
  { slug: 'grocery-supermarket',    name: 'Grocery & Supermarket',    nameMl: 'ഗ്രോസറി & സൂപ്പർമാർക്കറ്റ്',  count: 0 },
  { slug: 'real-estate',            name: 'Real Estate',              nameMl: 'റിയൽ എസ്റ്റേറ്റ്',             count: 0 },
  { slug: 'healthcare-medical',     name: 'Healthcare & Medical',     nameMl: 'ആരോഗ്യം & മെഡിക്കൽ',          count: 0 },
  { slug: 'education-training',     name: 'Education & Training',     nameMl: 'വിദ്യാഭ്യാസം & പരിശീലനം',     count: 0 },
  { slug: 'beauty-wellness',        name: 'Beauty & Wellness',        nameMl: 'സൗന്ദര്യം & ആരോഗ്യം',         count: 0 },
  { slug: 'technology-it',          name: 'Technology & IT',          nameMl: 'ടെക്നോളജി & ഐടി',             count: 0 },
  { slug: 'construction-interiors', name: 'Construction & Interiors', nameMl: 'നിർമ്മാണം & ഇന്റീരിയർ',      count: 0 },
  { slug: 'retail-fashion',         name: 'Retail & Fashion',         nameMl: 'റീടെയ്ൽ & ഫാഷൻ',             count: 0 },
  { slug: 'legal-finance',          name: 'Legal & Finance',          nameMl: 'നിയമം & ഫിനാൻസ്',             count: 0 },
  { slug: 'travel-tourism',         name: 'Travel & Tourism',         nameMl: 'യാത്ര & ടൂറിസം',              count: 0 },
  { slug: 'automotive',             name: 'Automotive',               nameMl: 'ഓട്ടോമോട്ടീവ്',               count: 0 },
]

// Slugs match exactly what's stored in listings.emirate in Supabase (underscore format)
export const emirates = [
  { slug: 'dubai',          name: 'Dubai',          nameMl: 'ദുബായ്',         count: 0 },
  { slug: 'abu_dhabi',      name: 'Abu Dhabi',      nameMl: 'അബുദാബി',        count: 0 },
  { slug: 'sharjah',        name: 'Sharjah',        nameMl: 'ഷാർജ',           count: 0 },
  { slug: 'ajman',          name: 'Ajman',          nameMl: 'അജ്മാൻ',         count: 0 },
  { slug: 'ras_al_khaimah', name: 'Ras Al Khaimah', nameMl: 'റാസ് അൽ ഖൈമ',  count: 0 },
  { slug: 'fujairah',       name: 'Fujairah',       nameMl: 'ഫുജൈറ',          count: 0 },
  { slug: 'umm_al_quwain',  name: 'Umm Al Quwain',  nameMl: 'ഉം അൽ ഖുവൈൻ', count: 0 },
]
