export type Classified = {
  id: number
  title: string
  titleMl: string
  description: string
  descriptionMl: string
  category: string
  categoryMl: string
  categorySlug: string
  subcategory: string
  price: string
  negotiable: boolean
  type: 'sale' | 'rent' | 'wanted' | 'service'
  location: string
  locationMl: string
  emirate: string
  postedAt: string
  postedAtMl: string
  seller: string
  sellerMl: string
  sellerAvatar: string
  phone: string
  whatsapp: string
  images: string[]
  views: number
  featured: boolean
  urgent: boolean
  condition?: 'new' | 'like-new' | 'good' | 'fair'
}

export const classifiedCategories = [
  { slug: 'vehicles', name: 'Vehicles', nameMl: 'വാഹനങ്ങൾ', icon: '🚗', count: 842 },
  { slug: 'property', name: 'Property', nameMl: 'പ്രോപ്പർടി', icon: '🏠', count: 1240 },
  { slug: 'electronics', name: 'Electronics', nameMl: 'ഇലക്ട്രോണിക്സ്', icon: '📱', count: 678 },
  { slug: 'furniture', name: 'Furniture', nameMl: 'ഫർണിച്ചർ', icon: '🛋️', count: 432 },
  { slug: 'jobs', name: 'Jobs & Services', nameMl: 'ജോലി & സേവനം', icon: '💼', count: 956 },
  { slug: 'fashion', name: 'Fashion', nameMl: 'ഫാഷൻ', icon: '👗', count: 324 },
  { slug: 'food', name: 'Food & Homemade', nameMl: 'ഭക്ഷണം & ഹോം', icon: '🍲', count: 287 },
  { slug: 'kids', name: 'Kids & Baby', nameMl: 'കുട്ടികൾ & ബേബി', icon: '👶', count: 198 },
  { slug: 'books', name: 'Books & Education', nameMl: 'പുസ്തകം & വിദ്യ', icon: '📚', count: 143 },
  { slug: 'community', name: 'Community Help', nameMl: 'കമ്മ്യൂണിറ്റി', icon: '🤝', count: 89 },
]

export const mockClassifieds: Classified[] = [
  {
    id: 1,
    title: '2021 Toyota Camry 2.5L — Excellent Condition',
    titleMl: '2021 ടൊയോട്ട കാമ്രി 2.5L — മികച്ച അവസ്ഥ',
    description: 'Single owner, full service history with Toyota. Only 42,000km. No accidents. GCC spec, sunroof, leather seats, reverse camera. Selling due to relocation to Kerala.',
    descriptionMl: 'ഒറ്റ ഉടമ, ടൊയോട്ടയുടെ പൂർണ്ണ സർവ്വീസ് ഹിസ്‌റ്ററി. 42,000km മാത്രം. അപകടങ്ങൾ ഇല്ല. GCC സ്‌പെക്. കേരളത്തിലേക്ക് പോകുന്നതിനാൽ വിൽക്കുന്നു.',
    category: 'Vehicles',
    categoryMl: 'വാഹനങ്ങൾ',
    categorySlug: 'vehicles',
    subcategory: 'Cars',
    price: 'AED 58,000',
    negotiable: true,
    type: 'sale',
    location: 'Deira, Dubai',
    locationMl: 'ദേര, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '2 hours ago',
    postedAtMl: '2 മണിക്കൂർ മുൻപ്',
    seller: 'Arun Krishnan',
    sellerMl: 'അരുൺ കൃഷ്ണൻ',
    sellerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    phone: '+971 50 234 5678',
    whatsapp: '+971 50 234 5678',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80&auto=format&fit=crop',
    ],
    views: 284,
    featured: true,
    urgent: false,
    condition: 'like-new',
  },
  {
    id: 2,
    title: '2BHK Apartment for Rent — Al Nahda, Sharjah',
    titleMl: '2BHK ഫ്ലാറ്റ് വാടകയ്ക്ക് — അൽ നഹ്ദ, ഷാർജ',
    description: 'Spacious 2BHK on 5th floor, fully maintained. Close to Sahara Centre. Covered parking, gym, pool. AED 42,000/yr or AED 3,800/mo. Available immediately. Prefer Malayali family.',
    descriptionMl: '5-ആം നിലയിൽ വിശാലമായ 2BHK. സഹാറ സെന്ററിനടുത്ത്. കവേർഡ് പാർക്കിംഗ്, ജിം, പൂൾ. ഉടൻ ലഭ്യം. മലയാളി കുടുംബത്തിന് മുൻഗണന.',
    category: 'Property',
    categoryMl: 'പ്രോപ്പർടി',
    categorySlug: 'property',
    subcategory: 'Apartments',
    price: 'AED 42,000/yr',
    negotiable: false,
    type: 'rent',
    location: 'Al Nahda, Sharjah',
    locationMl: 'അൽ നഹ്ദ, ഷാർജ',
    emirate: 'Sharjah',
    postedAt: '5 hours ago',
    postedAtMl: '5 മണിക്കൂർ മുൻപ്',
    seller: 'Priya Nair',
    sellerMl: 'പ്രിയ നായർ',
    sellerAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    phone: '+971 52 345 6789',
    whatsapp: '+971 52 345 6789',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop',
    ],
    views: 512,
    featured: true,
    urgent: false,
  },
  {
    id: 3,
    title: 'iPhone 15 Pro Max 256GB Natural Titanium',
    titleMl: 'iPhone 15 Pro Max 256GB നാച്ചുറൽ ടൈറ്റേനിയം',
    description: 'Bought 3 months ago, switching to Android. Comes with original box, charger, unused screen protector. No scratches. Face ID works perfectly. Warranty until March 2025.',
    descriptionMl: '3 മാസം മുൻപ് വാങ്ങി. ഒറിജിനൽ ബോക്സ്, ചാർജർ സഹിതം. സ്ക്രാച്ചുകൾ ഇല്ല. മാർച്ച് 2025 വരെ വാറന്റി.',
    category: 'Electronics',
    categoryMl: 'ഇലക്ട്രോണിക്സ്',
    categorySlug: 'electronics',
    subcategory: 'Mobile Phones',
    price: 'AED 3,800',
    negotiable: true,
    type: 'sale',
    location: 'Al Reem, Abu Dhabi',
    locationMl: 'അൽ റീം, അബുദാബി',
    emirate: 'Abu Dhabi',
    postedAt: '1 day ago',
    postedAtMl: '1 ദിവസം മുൻപ്',
    seller: 'Rajan Pillai',
    sellerMl: 'രാജൻ പിള്ള',
    sellerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    phone: '+971 55 456 7890',
    whatsapp: '+971 55 456 7890',
    images: [
      'https://images.unsplash.com/photo-1696446701796-da61225697cc?w=800&q=80&auto=format&fit=crop',
    ],
    views: 198,
    featured: false,
    urgent: true,
    condition: 'like-new',
  },
  {
    id: 4,
    title: 'Malayalam-Speaking Nanny / Babysitter Needed',
    titleMl: 'മലയാളം സംസാരിക്കുന്ന ബേബിസിറ്റർ ആവശ്യം',
    description: 'Looking for an experienced, trustworthy Malayalam-speaking nanny for 2 kids (ages 3 & 6) in Dubai Marina. Live-in preferred. Salary negotiable. Good accommodation provided.',
    descriptionMl: 'ദുബായ് മറിനയിൽ 2 കുട്ടികൾക്ക് (3 & 6 വയസ്സ്) മലയാളം ബേബിസിറ്റർ ആവശ്യം. ലൈവ്-ഇൻ ആയിരിക്കണം. ശമ്പളം ചർച്ചചെയ്യാം. ഭക്ഷണം & താമസം ഉൾപ്പെടെ.',
    category: 'Jobs & Services',
    categoryMl: 'ജോലി & സേവനം',
    categorySlug: 'jobs',
    subcategory: 'Domestic Help',
    price: 'AED 2,500/mo',
    negotiable: true,
    type: 'wanted',
    location: 'Dubai Marina, Dubai',
    locationMl: 'ദുബായ് മറിന, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '3 hours ago',
    postedAtMl: '3 മണിക്കൂർ മുൻപ്',
    seller: 'Meera Menon',
    sellerMl: 'മീര മേനോൻ',
    sellerAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    phone: '+971 56 567 8901',
    whatsapp: '+971 56 567 8901',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80&auto=format&fit=crop',
    ],
    views: 89,
    featured: false,
    urgent: true,
  },
  {
    id: 5,
    title: 'Kerala Homemade Pickles & Pappadam — Bulk Orders Welcome',
    titleMl: 'കേരള ഹോം മെയ്ഡ് അച്ചാർ & പപ്പടം — ബൾക്ക് ഓർഡർ',
    description: 'Authentic Kerala homemade mango pickle (naranga achar), raw mango, and crispy Kerala pappadam. Made fresh with traditional recipes. Free delivery in Ajman & Sharjah for orders above AED 80.',
    descriptionMl: 'ആധികാരിക കേരള ഹോം മെയ്ഡ് നാരങ്ങ അച്ചാർ, മാമ്പഴ അച്ചാർ, പപ്പടം. AED 80-ന് മുകളിൽ ഓർഡറിന് അജ്മാൻ & ഷാർജ ഡെലിവറി സൗജന്യം.',
    category: 'Food & Homemade',
    categoryMl: 'ഭക്ഷണം & ഹോം',
    categorySlug: 'food',
    subcategory: 'Homemade Food',
    price: 'AED 25–80',
    negotiable: false,
    type: 'sale',
    location: 'Al Nuaimia, Ajman',
    locationMl: 'അൽ നുയൈമിയ, അജ്മാൻ',
    emirate: 'Ajman',
    postedAt: '6 hours ago',
    postedAtMl: '6 മണിക്കൂർ മുൻപ്',
    seller: 'Suma Thomas',
    sellerMl: 'സുമ തോമസ്',
    sellerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80',
    phone: '+971 50 678 9012',
    whatsapp: '+971 50 678 9012',
    images: [
      'https://images.unsplash.com/photo-1564894809611-1742fc40ed80?w=800&q=80&auto=format&fit=crop',
    ],
    views: 341,
    featured: false,
    urgent: false,
  },
  {
    id: 6,
    title: 'Office Space for Rent — Business Bay, 600 sqft',
    titleMl: 'ഓഫീസ് സ്ഥലം വാടകയ്ക്ക് — ബിസിനസ് ബേ, 600 sqft',
    description: 'Fully furnished office space in prime Business Bay location. Floor-to-ceiling windows, meeting room access, dedicated parking. Suitable for 5–8 person team. Ejari ready.',
    descriptionMl: 'പ്രൈം ബിസിനസ് ബേ ലൊക്കേഷൻ. ഫർണിഷ്ഡ്, മീറ്റിംഗ് റൂം, ഡെഡിക്കേറ്റഡ് പാർക്കിംഗ്. 5–8 പേർക്കുള്ള ടീം. Ejari റെഡി.',
    category: 'Property',
    categoryMl: 'പ്രോപ്പർടി',
    categorySlug: 'property',
    subcategory: 'Commercial',
    price: 'AED 6,500/mo',
    negotiable: true,
    type: 'rent',
    location: 'Business Bay, Dubai',
    locationMl: 'ബിസിനസ് ബേ, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '12 hours ago',
    postedAtMl: '12 മണിക്കൂർ മുൻപ്',
    seller: 'Vishnu Kumar',
    sellerMl: 'വിഷ്ണു കുമാർ',
    sellerAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
    phone: '+971 54 789 0123',
    whatsapp: '+971 54 789 0123',
    images: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=80&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop',
    ],
    views: 167,
    featured: true,
    urgent: false,
  },
  {
    id: 7,
    title: 'Kasavu Saree — Brand New, Handloom Kerala',
    titleMl: 'കസവ് സാരി — പുതിയത്, ഹൻഡ്‌ലൂം കേരളം',
    description: 'Pure cotton kasavu saree with gold zari border. Bought from Seematti, Kerala. Never worn. Original price AED 280. Selling at AED 180. Perfect for Onam. Pickup in Karama.',
    descriptionMl: 'ശുദ്ധ കോട്ടൺ കസവ് സാരി, ഗോൾഡ് സരി ബോർഡർ. കേരളം Seematti-ൽ നിന്ന് വാങ്ങിയത്. ഒരിക്കലും ധരിച്ചിട്ടില്ല. ഓണത്തിന് ഏറ്റവും അനുയോജ്യം.',
    category: 'Fashion',
    categoryMl: 'ഫാഷൻ',
    categorySlug: 'fashion',
    subcategory: 'Traditional Wear',
    price: 'AED 180',
    negotiable: false,
    type: 'sale',
    location: 'Karama, Dubai',
    locationMl: 'കരാമ, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '2 days ago',
    postedAtMl: '2 ദിവസം മുൻപ്',
    seller: 'Lakshmi Varma',
    sellerMl: 'ലക്ഷ്മി വർമ്മ',
    sellerAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&q=80',
    phone: '+971 55 890 1234',
    whatsapp: '+971 55 890 1234',
    images: [
      'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&q=80&auto=format&fit=crop',
    ],
    views: 423,
    featured: false,
    urgent: false,
    condition: 'new',
  },
  {
    id: 8,
    title: 'CBSE Tutor Needed for Grade 10 Maths & Science',
    titleMl: 'ഗ്രേഡ് 10 മാത്സ് & സയൻസ് CBSE ട്യൂഷൻ ആവശ്യം',
    description: 'Looking for an experienced CBSE tutor for Grade 10 Maths and Science in Sharjah. Classes 3x per week at home. Evening preferred. Malayalam-speaking tutor preferred. Salary open.',
    descriptionMl: 'ഷാർജ ഹോമിൽ ഗ്രേഡ് 10 CBSE മാത്സ് & സയൻസ് ട്യൂഷൻ. ആഴ്ചയിൽ 3 ക്ലാസ്. വൈകിട്ട് ആണ് ഇഷ്ടം. മലയാളം ടീച്ചർ ആണ് ആദ്യ ഓപ്ഷൻ.',
    category: 'Books & Education',
    categoryMl: 'പുസ്തകം & വിദ്യ',
    categorySlug: 'books',
    subcategory: 'Tutoring',
    price: 'AED 80/hr',
    negotiable: true,
    type: 'wanted',
    location: 'Muweilah, Sharjah',
    locationMl: 'മുവൈല, ഷാർജ',
    emirate: 'Sharjah',
    postedAt: '4 hours ago',
    postedAtMl: '4 മണിക്കൂർ മുൻപ്',
    seller: 'Thomas George',
    sellerMl: 'തോമസ് ജോർജ്',
    sellerAvatar: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=100&q=80',
    phone: '+971 50 901 2345',
    whatsapp: '+971 50 901 2345',
    images: [
      'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80&auto=format&fit=crop',
    ],
    views: 76,
    featured: false,
    urgent: false,
  },
  {
    id: 9,
    title: 'Samsung 65" QLED TV — Like New, Selling Urgently',
    titleMl: 'Samsung 65" QLED TV — ഏതാണ്ട് പുതിയത്, അർജന്റ് വിൽക്കുന്നു',
    description: 'Samsung 65" Q80C QLED 4K 2023 model. Used 8 months. Selling due to relocation. Original remote, wall mount, box included. Asking AED 2,200, was AED 3,800 new.',
    descriptionMl: 'Samsung 65" Q80C QLED 4K 2023 മോഡൽ. 8 മാസം ഉപയോഗം. ട്രാൻസ്ഫർ ആകുന്നതിനാൽ വിൽക്കുന്നു. ഒറിജിനൽ ബോക്സ്, വോൾ മൗണ്ട് ഉൾപ്പെടെ.',
    category: 'Electronics',
    categoryMl: 'ഇലക്ട്രോണിക്സ്',
    categorySlug: 'electronics',
    subcategory: 'TVs',
    price: 'AED 2,200',
    negotiable: true,
    type: 'sale',
    location: 'JBR, Dubai',
    locationMl: 'JBR, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '8 hours ago',
    postedAtMl: '8 മണിക്കൂർ മുൻപ്',
    seller: 'Deepak Nambiar',
    sellerMl: 'ദീപക് നമ്പ്യാർ',
    sellerAvatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=100&q=80',
    phone: '+971 52 012 3456',
    whatsapp: '+971 52 012 3456',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=800&q=80&auto=format&fit=crop',
    ],
    views: 312,
    featured: false,
    urgent: true,
    condition: 'like-new',
  },
  {
    id: 10,
    title: 'Handmade Kerala Murals — Commission & Ready Pieces',
    titleMl: 'ഹൻഡ്‌മെയ്ഡ് കേരള മ്യൂറൽ — കമ്മീഷൻ & റെഡി',
    description: 'Professional Kerala mural artist based in Dubai. Accepting commissions for homes and offices. Ready-made pieces (A3 to 4x6 ft) also available. All natural colours. DM for portfolio.',
    descriptionMl: 'ദുബായ് ആസ്ഥാനമായ കേരള മ്യൂറൽ ആർടിസ്റ്റ്. ഹോം & ഓഫീസ് കമ്മീഷൻ. റെഡിമെയ്ഡ് പീസ് ലഭ്യം. പ്രകൃതി നിറങ്ങൾ. പോർട്ട്‌ഫോളിയോ DM-ൽ.',
    category: 'Community Help',
    categoryMl: 'കമ്മ്യൂണിറ്റി',
    categorySlug: 'community',
    subcategory: 'Art & Crafts',
    price: 'AED 250+',
    negotiable: true,
    type: 'service',
    location: 'Al Quoz, Dubai',
    locationMl: 'അൽ ഖൊസ്, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '1 day ago',
    postedAtMl: '1 ദിവസം മുൻപ്',
    seller: 'Anitha Krishnamoorthi',
    sellerMl: 'അനിത കൃഷ്ണമൂർത്തി',
    sellerAvatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=100&q=80',
    phone: '+971 56 123 4567',
    whatsapp: '+971 56 123 4567',
    images: [
      'https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=800&q=80&auto=format&fit=crop',
    ],
    views: 189,
    featured: false,
    urgent: false,
  },
  {
    id: 11,
    title: 'Sofa Set 3+2 — Good Condition, Moving Sale',
    titleMl: 'സോഫ സെറ്റ് 3+2 — നല്ല അവസ്ഥ, മൂവിംഗ് സെയ്ൽ',
    description: 'Brown leather sofa set (3+2 seater), good condition. 2 years old. Minor scuffs on one armrest, nothing major. Asking AED 900. Buyer arranges pickup from Ajman.',
    descriptionMl: 'ബ്രൗൺ ലെതർ സോഫ സെറ്റ് (3+2), നല്ല അവസ്ഥ. 2 വർഷം പഴക്കം. ഒരു ആംറെസ്റ്റിൽ ചെറിയ സ്ക്രാച്ച്. AED 900. ബയർ തന്നെ പിക്ക്അപ് ചെയ്യണം.',
    category: 'Furniture',
    categoryMl: 'ഫർണിച്ചർ',
    categorySlug: 'furniture',
    subcategory: 'Sofas',
    price: 'AED 900',
    negotiable: true,
    type: 'sale',
    location: 'Al Rashidiya, Ajman',
    locationMl: 'അൽ റഷിദിയ, അജ്മാൻ',
    emirate: 'Ajman',
    postedAt: '3 days ago',
    postedAtMl: '3 ദിവസം മുൻപ്',
    seller: 'Suresh Babu',
    sellerMl: 'സുരേഷ് ബാബു',
    sellerAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&q=80',
    phone: '+971 50 234 5678',
    whatsapp: '+971 50 234 5678',
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80&auto=format&fit=crop',
    ],
    views: 97,
    featured: false,
    urgent: false,
    condition: 'good',
  },
  {
    id: 12,
    title: 'Baby Pram & Car Seat — Barely Used',
    titleMl: 'ബേബി പ്രാം & കാർ സീറ്റ് — ഏതാണ്ട് ഉപയോഗിക്കാത്തത്',
    description: 'Chicco travel system: Activ3 pram + KeyFit 35 infant car seat combo. Used for 4 months only. All attachments, bag, rain cover included. AED 700 firm, worth AED 1,600 new.',
    descriptionMl: 'Chicco ട്രാവൽ സിസ്റ്റം: Activ3 പ്രാം + KeyFit 35 ഇൻഫന്റ് കാർ സീറ്റ്. 4 മാസം മാത്രം ഉപയോഗം. എല്ലാ അറ്റാച്ച്‌മെൻ്റ്സ്, ബാഗ്, റൈൻ കവർ ഉൾപ്പെടെ.',
    category: 'Kids & Baby',
    categoryMl: 'കുട്ടികൾ & ബേബി',
    categorySlug: 'kids',
    subcategory: 'Prams',
    price: 'AED 700',
    negotiable: false,
    type: 'sale',
    location: 'Mirdif, Dubai',
    locationMl: 'മർദ്ദിഫ്, ദുബായ്',
    emirate: 'Dubai',
    postedAt: '5 hours ago',
    postedAtMl: '5 മണിക്കൂർ മുൻപ്',
    seller: 'Divya Suresh',
    sellerMl: 'ദിവ്യ സുരേഷ്',
    sellerAvatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=100&q=80',
    phone: '+971 52 345 6789',
    whatsapp: '+971 52 345 6789',
    images: [
      'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?w=800&q=80&auto=format&fit=crop',
    ],
    views: 203,
    featured: false,
    urgent: false,
    condition: 'like-new',
  },
]
